# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'card_scanner.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ScanWindow(object):
    def setupUi(self, ScanWindow):
        ScanWindow.setObjectName("ScanWindow")
        ScanWindow.resize(400, 170)
        self.buttonBox = QtWidgets.QDialogButtonBox(ScanWindow)
        self.buttonBox.setGeometry(QtCore.QRect(30, 110, 341, 32))
        self.buttonBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel)
        self.buttonBox.setCenterButtons(True)
        self.buttonBox.setObjectName("buttonBox")
        self.label = QtWidgets.QLabel(ScanWindow)
        self.label.setGeometry(QtCore.QRect(100, 20, 201, 31))
        self.label.setStyleSheet("font: 8pt \"BR Cobane\";\n"
"color: rgb(255, 255, 255);\n"
"font: 11pt \"MS Shell Dlg 2\";")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(ScanWindow)
        self.label_2.setGeometry(QtCore.QRect(50, 50, 121, 60))
        self.label_2.setStyleSheet("font: 57 18pt \"BR Cobane Medium\";\n"
"color: rgb(255, 200, 21);")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(ScanWindow)
        self.label_3.setGeometry(QtCore.QRect(100, 50, 271, 60))
        self.label_3.setStyleSheet("font: 57 18pt \"BR Cobane Medium\";\n"
"color: rgb(255, 200, 21);")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.frame = QtWidgets.QFrame(ScanWindow)
        self.frame.setGeometry(QtCore.QRect(0, 0, 400, 170))
        self.frame.setStyleSheet("background-image: url(:/background/assets/scan_card_bg.png);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.frame.raise_()
        self.buttonBox.raise_()
        self.label.raise_()
        self.label_2.raise_()
        self.label_3.raise_()

        self.retranslateUi(ScanWindow)
        self.buttonBox.accepted.connect(ScanWindow.accept) # type: ignore
        self.buttonBox.rejected.connect(ScanWindow.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(ScanWindow)

    def retranslateUi(self, ScanWindow):
        _translate = QtCore.QCoreApplication.translate
        ScanWindow.setWindowTitle(_translate("ScanWindow", "Card Scanner"))
        self.label.setText(_translate("ScanWindow", "Please scan your card"))
        self.label_2.setText(_translate("ScanWindow", "ID:   "))
import resources_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ScanWindow = QtWidgets.QDialog()
    ui = Ui_ScanWindow()
    ui.setupUi(ScanWindow)
    ScanWindow.show()
    sys.exit(app.exec_())
