# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'confirmation.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
#from main_page import Ui_MainWindow

class Ui_Confirmation(object):

    def mainWindow(self):
            self.window = QtWidgets.QMainWindow()
            self.ui = Ui_MainWindow()
            self.ui.setupUi(self.window)
            self.window.show()

    def setupUi(self, Confirmation):
        Confirmation.setObjectName("Confirmation")
        Confirmation.resize(400, 106)
        self.buttonBox = QtWidgets.QDialogButtonBox(Confirmation)
        self.buttonBox.setGeometry(QtCore.QRect(30, 60, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.label = QtWidgets.QLabel(Confirmation)
        self.label.setGeometry(QtCore.QRect(30, 10, 281, 51))
        self.label.setObjectName("label")

        self.retranslateUi(Confirmation)
        self.buttonBox.accepted.connect(Confirmation.accept) # type: ignore
        self.buttonBox.rejected.connect(Confirmation.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Confirmation)

    def retranslateUi(self, Confirmation):
        _translate = QtCore.QCoreApplication.translate
        Confirmation.setWindowTitle(_translate("Confirmation", "Confirmation"))
        self.label.setText(_translate("Confirmation", "Are you sure you want to go back to the main page?"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Confirmation = QtWidgets.QDialog()
    ui = Ui_Confirmation()
    ui.setupUi(Confirmation)
    Confirmation.show()
    sys.exit(app.exec_())
