from time import strptime
from PyQt5 import QtCore, QtGui, QtWidgets
from helper_functions import getUserWorkouts, displayWorkout, db
workoutsList = None
filename = None

class Ui_WorkoutsWindow(object):
    user_id = None
    
    def showWorkout(self):

        print(filename)
        displayWorkout(filename[0])
        #print(workoutNumber)

    def showWorkoutDetails(self, value):
        from datetime import timedelta, datetime
        global workoutsList, filename
        workout = self.comboBox.currentText()
        (_,workoutNumber,_,_,_) = workout.split(" ")
        workoutNumber = int(workoutNumber)-1
        filename = self.comboBox.currentData()
        con = db()
        cur = con.cursor()
        cur.execute('SELECT timestamp,end_time,distance,max_speed FROM sessions WHERE filename = (?)', (str(filename[0]),))
        data = cur.fetchall()
        (timestamp, end_time, distance, max_speed) = data[0]
        end_time = datetime.strptime(end_time, "%Y-%m-%d %H:%M:%S.%f")
        timestamp = datetime.strptime(timestamp, "%Y-%m-%d %H:%M:%S.%f")
        time = end_time - timestamp
        self.distanceOutput.setText(str("{:.2f}".format(distance)) + ' meters')
        self.averageSpeedOutput.setText(str("{:.2f}".format((distance/1000)/(time.total_seconds()/3600))) + ' km/h')
        self.timeOutput.setText(str(time))
        self.topSpeedOutput.setText(str("{:.2f}".format(max_speed)) + ' km/h')
        print(data)
    
    def setupUi(self, WorkoutsWindow):
        WorkoutsWindow.setObjectName("WorkoutsWindow")
        WorkoutsWindow.resize(1024, 600)
        WorkoutsWindow.setWindowFlag(QtCore.Qt.FramelessWindowHint)
        self.centralwidget = QtWidgets.QWidget(WorkoutsWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(70, 60, 791, 51))
        font = QtGui.QFont()
        font.setFamily("BR Cobane")
        font.setPointSize(32)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(255, 200, 21);")
        self.label.setObjectName("label")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(130, 280, 241, 31))
        self.comboBox.setStyleSheet("background-color: rgb(255, 200, 21);\n"
        
"color: rgb(41, 41, 41);")
        self.comboBox.setObjectName("comboBox")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 1024, 600))
        self.frame.setStyleSheet("background-image: url(:/background/assets/empty_background.png);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(130, 240, 201, 31))
        font = QtGui.QFont()
        font.setFamily("BR Cobane Light")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("\n"
"color: rgb(255, 200, 21);")
        self.label_2.setObjectName("label_2")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(420, 140, 611, 411))
        self.frame_2.setStyleSheet("font: 14pt \"BR Cobane\";\n"
"color: rgb(255, 200, 21);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.formLayoutWidget_2 = QtWidgets.QWidget(self.frame_2)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(40, 30, 601, 261))
        self.formLayoutWidget_2.setObjectName("formLayoutWidget_2")
        self.formLayout_2 = QtWidgets.QFormLayout(self.formLayoutWidget_2)
        self.formLayout_2.setLabelAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.formLayout_2.setFormAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.formLayout_2.setObjectName("formLayout_2")
        self.distanceLabel = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.distanceLabel.setObjectName("distanceLabel")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.distanceLabel)
        self.distanceOutput = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.distanceOutput.setText("")
        self.distanceOutput.setObjectName("distanceOutput")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.distanceOutput)
        self.averageSpeedLabel = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.averageSpeedLabel.setObjectName("averageSpeedLabel")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.averageSpeedLabel)
        self.averageSpeedOutput = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.averageSpeedOutput.setText("")
        self.averageSpeedOutput.setObjectName("averageSpeedOutput")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.averageSpeedOutput)
        self.topSpeedLabel = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.topSpeedLabel.setObjectName("topSpeedLabel")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.topSpeedLabel)
        self.topSpeedOutput = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.topSpeedOutput.setText("")
        self.topSpeedOutput.setObjectName("topSpeedOutput")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.topSpeedOutput)
        self.timeLabel = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.timeLabel.setObjectName("timeLabel")
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.timeLabel)
        self.timeOutput = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.timeOutput.setText("")
        self.timeOutput.setObjectName("timeOutput")
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.timeOutput)
        self.avgPowerLabel = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.avgPowerLabel.setObjectName("avgPowerLabel")
        self.formLayout_2.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.avgPowerLabel)
        self.avgPowerOutput = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.avgPowerOutput.setText("")
        self.avgPowerOutput.setObjectName("avgPowerOutput")
        self.formLayout_2.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.avgPowerOutput)
        spacerItem = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout_2.setItem(1, QtWidgets.QFormLayout.LabelRole, spacerItem)
        spacerItem1 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout_2.setItem(3, QtWidgets.QFormLayout.LabelRole, spacerItem1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout_2.setItem(5, QtWidgets.QFormLayout.LabelRole, spacerItem2)
        spacerItem3 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout_2.setItem(7, QtWidgets.QFormLayout.LabelRole, spacerItem3)
        self.pointsLabel = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.pointsLabel.setObjectName("pointsLabel")
        self.formLayout_2.setWidget(10, QtWidgets.QFormLayout.LabelRole, self.pointsLabel)
        spacerItem4 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout_2.setItem(9, QtWidgets.QFormLayout.LabelRole, spacerItem4)
        self.commandLinkButton = QtWidgets.QCommandLinkButton(self.centralwidget)
        self.commandLinkButton.setGeometry(QtCore.QRect(20, 20, 80, 40))
        self.commandLinkButton.setStyleSheet("color: rgb(255, 200, 21);\n"
"selection-background-color: rgba(255, 255, 255, 0);\n"
"selection-color: rgba(255, 255, 255, 0);\n"
"border: transparent;")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("assets/arrow-left-solid-yellow.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.commandLinkButton.setIcon(icon)
        self.commandLinkButton.setObjectName("commandLinkButton")
        self.commandLinkButton.clicked.connect(WorkoutsWindow.close)
        self.viewWorkoutButton = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.showWorkout())
        self.viewWorkoutButton.setEnabled(True)
        self.viewWorkoutButton.setGeometry(QtCore.QRect(130, 360, 230, 80))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.viewWorkoutButton.sizePolicy().hasHeightForWidth())
        self.viewWorkoutButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("BR Cobane")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(True)
        self.viewWorkoutButton.setFont(font)
        self.viewWorkoutButton.setAutoFillBackground(False)
        self.viewWorkoutButton.setStyleSheet("background-color: rgb(41, 41, 41);\n"
"border: 2px solid rgb(255, 200, 21);\n"
"color: rgb(255, 200, 21);")
        self.viewWorkoutButton.setDefault(False)
        self.viewWorkoutButton.setFlat(False)
        self.viewWorkoutButton.setObjectName("viewWorkoutButton")
        self.frame.raise_()
        self.label.raise_()
        self.comboBox.raise_()
        self.label_2.raise_()
        self.frame_2.raise_()
        self.commandLinkButton.raise_()
        self.viewWorkoutButton.raise_()
        WorkoutsWindow.setCentralWidget(self.centralwidget)

        self.comboBox.currentIndexChanged.connect(self.showWorkoutDetails, self.comboBox.currentIndex())

        self.retranslateUi(WorkoutsWindow)
        QtCore.QMetaObject.connectSlotsByName(WorkoutsWindow)

    def retranslateUi(self, WorkoutsWindow):
        _translate = QtCore.QCoreApplication.translate
        WorkoutsWindow.setWindowTitle(_translate("WorkoutsWindow", "Your Workouts"))
        self.label.setText(_translate("WorkoutsWindow", "YOUR WORKOUTS"))
        self.label_2.setText(_translate("WorkoutsWindow", "Select a workout: "))
        self.distanceLabel.setText(_translate("WorkoutsWindow", "Distance: "))
        self.averageSpeedLabel.setText(_translate("WorkoutsWindow", "Average Speed: "))
        self.topSpeedLabel.setText(_translate("WorkoutsWindow", "Top Speed: "))
        self.timeLabel.setText(_translate("WorkoutsWindow", "Workout Duration: "))
        self.avgPowerLabel.setText(_translate("WorkoutsWindow", "Average Power: "))
        self.pointsLabel.setText(_translate("WorkoutsWindow", "Points: "))
        self.commandLinkButton.setText(_translate("WorkoutsWindow", "Home"))
        self.viewWorkoutButton.setText(_translate("WorkoutsWindow", "VIEW WORKOUT"))
import resources_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    WorkoutsWindow = QtWidgets.QMainWindow()
    ui = Ui_WorkoutsWindow()
    ui.setupUi(WorkoutsWindow)
    WorkoutsWindow.show()
    sys.exit(app.exec_())
