# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'registration_page.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import helper_functions
import threading
from datetime import datetime

user_id = None

class Ui_RegisterWindow(object):
        def fetchUserData(self): #gets used data from text boxes (user input)
                data = []
                #data = [id, dor, firstName, lastName, email, phone, sex, dob, weight, NULL, NULL, NULL]
                data.append(self.firstNameInput.text())
                data.append(self.lastNameInput.text())
                data.append(self.emailInput.text())
                data.append(self.phoneInput.text())
                data.append('M' if self.sexInput.currentText() == 'Male' else 'F' if self.sexInput.currentText() == 'Female' else 'O')
                data.append(self.dobInput.text())
                data.append(self.weightInput.text())
                print(data)
                return data

        def saveInfo(self): #register user in database
                data = []
                entered_data = self.fetchUserData()
                data.append(user_id)
                dor = datetime.today().strftime('%Y/%m/%d')
                data.append(dor)
                for _ in entered_data:
                        data.append(_)
                print(data)
                helper_functions.register_user(data)

        def mainWindow(self):
                from main_page import Ui_MainWindow
                self.window = QtWidgets.QMainWindow()
                self.ui = Ui_MainWindow()
                self.ui.setupUi(self.window)
                self.window.show()

        def setupUi(self, RegisterWindow):
                RegisterWindow.setObjectName("RegisterWindow")
                RegisterWindow.resize(1024, 600)
                self.centralwidget = QtWidgets.QWidget(RegisterWindow)
                self.centralwidget.setObjectName("centralwidget")
                self.frame = QtWidgets.QFrame(self.centralwidget)
                self.frame.setEnabled(True)
                self.frame.setGeometry(QtCore.QRect(120, 130, 571, 321))
                font = QtGui.QFont()
                font.setFamily("BR Cobane SemiBold")
                font.setPointSize(14)
                font.setBold(False)
                font.setItalic(False)
                font.setWeight(7)
                self.frame.setFont(font)
                self.frame.setLayoutDirection(QtCore.Qt.LeftToRight)
                self.frame.setStyleSheet("font: 63 14pt \"BR Cobane SemiBold\";")
                self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
                self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
                self.frame.setObjectName("frame")
                self.formLayoutWidget = QtWidgets.QWidget(self.frame)
                self.formLayoutWidget.setGeometry(QtCore.QRect(0, 20, 541, 311))
                self.formLayoutWidget.setObjectName("formLayoutWidget")
                self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
                self.formLayout.setLabelAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
                self.formLayout.setFormAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
                self.formLayout.setContentsMargins(0, 0, 0, 0)
                self.formLayout.setObjectName("formLayout")
                self.firstNameLabel = QtWidgets.QLabel(self.formLayoutWidget)
                self.firstNameLabel.setObjectName("firstNameLabel")
                self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.firstNameLabel)
                self.firstNameInput = QtWidgets.QLineEdit(self.formLayoutWidget)
                self.firstNameInput.setObjectName("firstNameInput")
                self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.firstNameInput)
                self.lastNameLabel = QtWidgets.QLabel(self.formLayoutWidget)
                self.lastNameLabel.setObjectName("lastNameLabel")
                self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.lastNameLabel)
                self.lastNameInput = QtWidgets.QLineEdit(self.formLayoutWidget)
                self.lastNameInput.setObjectName("lastNameInput")
                self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lastNameInput)
                self.emailLabel = QtWidgets.QLabel(self.formLayoutWidget)
                self.emailLabel.setObjectName("emailLabel")
                self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.emailLabel)
                self.emailInput = QtWidgets.QLineEdit(self.formLayoutWidget)
                self.emailInput.setObjectName("emailInput")
                self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.emailInput)
                self.phoneLabel = QtWidgets.QLabel(self.formLayoutWidget)
                self.phoneLabel.setObjectName("phoneLabel")
                self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.phoneLabel)
                self.phoneInput = QtWidgets.QLineEdit(self.formLayoutWidget)
                self.phoneInput.setObjectName("phoneInput")
                self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.phoneInput)
                self.sexLabel = QtWidgets.QLabel(self.formLayoutWidget)
                self.sexLabel.setObjectName("sexLabel")
                self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.sexLabel)
                self.sexInput = QtWidgets.QComboBox(self.formLayoutWidget)
                self.sexInput.setObjectName("sexInput")
                self.sexInput.addItem("")
                self.sexInput.addItem("")
                self.sexInput.addItem("")
                self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.sexInput)
                self.dobLabel = QtWidgets.QLabel(self.formLayoutWidget)
                self.dobLabel.setObjectName("dobLabel")
                self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.dobLabel)
                self.dobInput = QtWidgets.QDateEdit(self.formLayoutWidget)
                self.dobInput.setObjectName("dobInput")
                self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.dobInput)
                self.weightLabel = QtWidgets.QLabel(self.formLayoutWidget)
                self.weightLabel.setObjectName("weightLabel")
                self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.weightLabel)
                self.weightInput = QtWidgets.QLineEdit(self.formLayoutWidget)
                self.weightInput.setObjectName("weightInput")
                self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.weightInput)
                self.idLabel = QtWidgets.QLabel(self.formLayoutWidget)
                self.idLabel.setObjectName("idLabel")
                self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.idLabel)
                self.idOutput = QtWidgets.QLabel(self.formLayoutWidget)
                self.idOutput.setText("Please scan your ID card")
                self.idOutput.setObjectName("idOutput")
                self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.idOutput)
                self.saveButton = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.saveInfo())
                self.saveButton.setGeometry(QtCore.QRect(430, 480, 230, 80))
                font = QtGui.QFont()
                font.setFamily("BR Cobane")
                font.setPointSize(16)
                font.setBold(False)
                font.setWeight(50)
                self.saveButton.setFont(font)
                self.saveButton.setAutoFillBackground(False)
                self.saveButton.setStyleSheet("color: rgb(41, 41, 41);\n"
                "border-color: rgba(255, 255, 255, 0);\n"
                "background-color: rgb(255, 200, 21);\n"
                "border: 2px solid rgb(41, 41, 41);\n"
                "alternate-background-color: rgb(41, 41, 41);\n"
                "")
                self.saveButton.setAutoDefault(False)
                self.saveButton.setDefault(False)
                self.saveButton.setFlat(False)
                self.saveButton.setObjectName("saveButton")
                self.clearButton = QtWidgets.QPushButton(self.centralwidget)
                self.clearButton.setEnabled(True)
                self.clearButton.setGeometry(QtCore.QRect(120, 480, 230, 80))
                sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
                sizePolicy.setHorizontalStretch(0)
                sizePolicy.setVerticalStretch(0)
                sizePolicy.setHeightForWidth(self.clearButton.sizePolicy().hasHeightForWidth())
                self.clearButton.setSizePolicy(sizePolicy)
                font = QtGui.QFont()
                font.setFamily("BR Cobane")
                font.setPointSize(16)
                font.setBold(False)
                font.setWeight(50)
                font.setKerning(True)
                self.clearButton.setFont(font)
                self.clearButton.setAutoFillBackground(False)
                self.clearButton.setStyleSheet("background-color: rgb(41, 41, 41);\n"
                "border: 2px solid rgb(255, 200, 21);\n"
                "color: rgb(255, 200, 21);")
                self.clearButton.setDefault(False)
                self.clearButton.setFlat(False)
                self.clearButton.setObjectName("clearButton")
                self.frame_2 = QtWidgets.QFrame(self.centralwidget)
                self.frame_2.setGeometry(QtCore.QRect(0, 0, 1024, 600))
                self.frame_2.setStyleSheet("background-image: url(:/background/assets/registration_bg.png);")
                self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
                self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
                self.frame_2.setObjectName("frame_2")
                self.label = QtWidgets.QLabel(self.centralwidget)
                self.label.setGeometry(QtCore.QRect(70, 60, 791, 51))
                font = QtGui.QFont()
                font.setFamily("BR Cobane")
                font.setPointSize(32)
                font.setBold(True)
                font.setWeight(75)
                self.label.setFont(font)
                self.label.setObjectName("label")
                self.commandLinkButton_2 = QtWidgets.QCommandLinkButton(self.centralwidget, clicked = lambda: self.mainWindow())
                self.commandLinkButton_2.clicked.connect(RegisterWindow.close)
                self.commandLinkButton_2.setGeometry(QtCore.QRect(20, 20, 80, 40))
                self.commandLinkButton_2.setStyleSheet("color: rgb(41, 41, 41);\n"
                "selection-background-color: rgba(255, 255, 255, 0);\n"
                "selection-color: rgba(255, 255, 255, 0);\n"
                "border: transparent;")
                icon = QtGui.QIcon()
                icon.addPixmap(QtGui.QPixmap("assets/arrow-left-solid.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
                self.commandLinkButton_2.setIcon(icon)
                self.commandLinkButton_2.setObjectName("commandLinkButton_2")
                self.frame_2.raise_()
                self.frame.raise_()
                self.saveButton.raise_()
                self.label.raise_()
                self.clearButton.raise_()
                self.commandLinkButton_2.raise_()
                RegisterWindow.setCentralWidget(self.centralwidget)
                self.retranslateUi(RegisterWindow)
                QtCore.QMetaObject.connectSlotsByName(RegisterWindow)

        def retranslateUi(self, RegisterWindow):
                _translate = QtCore.QCoreApplication.translate
                RegisterWindow.setWindowTitle(_translate("RegisterWindow", "Registration"))
                self.firstNameLabel.setText(_translate("RegisterWindow", "First Name:   "))
                self.lastNameLabel.setText(_translate("RegisterWindow", "Last Name:   "))
                self.emailLabel.setText(_translate("RegisterWindow", "Email:   "))
                self.phoneLabel.setText(_translate("RegisterWindow", "Phone Number:   "))
                self.sexLabel.setText(_translate("RegisterWindow", "Sex:   "))
                self.sexInput.setItemText(0, _translate("RegisterWindow", "Male"))
                self.sexInput.setItemText(1, _translate("RegisterWindow", "Female"))
                self.sexInput.setItemText(2, _translate("RegisterWindow", "Other"))
                self.dobLabel.setText(_translate("RegisterWindow", "Date of Birth:   "))
                self.weightLabel.setText(_translate("RegisterWindow", "Weight:   "))
                self.idLabel.setText(_translate("RegisterWindow", "ID:   "))
                self.saveButton.setText(_translate("RegisterWindow", "SAVE"))
                self.clearButton.setText(_translate("RegisterWindow", "CLEAR"))
                self.label.setText(_translate("RegisterWindow", "THE META-GYM USER REGISTRATION"))
                self.commandLinkButton_2.setText(_translate("RegisterWindow", "Home"))

        def scanUpdate():
                global user_id
                while True:
                        user_id=str(helper_functions.scan_card_f())
                       # ui.idOutput.setText(user_id)
                        if user_id == '999888777':
                                break 

        scanner_thread = threading.Thread(target=scanUpdate)

import resources_rc


if __name__ == "__main__":
        import sys
        app = QtWidgets.QApplication(sys.argv)
        RegisterWindow = QtWidgets.QMainWindow()
        ui = Ui_RegisterWindow()
        ui.setupUi(RegisterWindow)
        RegisterWindow.show()
        ui.scanner_thread.start()
        sys.exit(app.exec_())

